name: Automatic Backport
description: Automatically backport commits based on commit tags or pull request labels
author: Ember.js
inputs:
  before:
    description: The SHA or ref of the most recent commit before the push.
    required: true
    default: ${{ github.event.before }}
  after:
    description: The SHA or ref of the most recent commit after the push.
    required: true
    default: ${{ github.event.after }}
  tags:
    description: A mapping of commit tags to branch names
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
